# dev 分支推送部署预览

name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"

      # 安装项目依赖
      - name: Install Dependencies
        run: npm install

      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # 上传构建产物
      - name: Upload artifacts
        # 链接 https://github.com/actions/upload-artifact/
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Blog
          path: public

  # TODO 同 HomePage ，分开跑

  deploy-gh-pages:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    needs: build  # 表示依赖于 build 作业完成
    steps:
      - name: Download artifact
        # 链接 https://github.com/actions/download-artifact
        uses: actions/download-artifact@v4.0.0
        with:
          name: Blog
          path: dist

      - name: Deploy to gh-pages
        # 链接 https://github.com/crazy-max/ghaction-github-pages/
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages
          build_dir: dist
          keep_history: true
          fqdn: blog.lzx0626.me
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}   

  deploy-server:
    name: Deploy to My Own Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.0.0
        with:
          name: Blog
          path: public

      - name: Deploy to My Own Server
        # 链接 https://github.com/easingthemes/ssh-deploy
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
